added handling and test for bare raise statements
heavenshell/py-doq pull request #101
Opened 2022-01-02 22:17 UTC by diego-ponce

Bare raise statements can be emitted from parso's module.iter_raise_statements which is used in `parser.py` when appending exceptions. These statements will have no children (no variable name assigned to the exception). This PR suggests appending an empty string to signify an exception but without a variable name.

2022-01-03 10:14 UTC, heavenshell requested changes
Thank you for PR!
LGTM but Flake8 shows error.
Please fix it and CI passes, I'll merge this!

2022-01-03 10:14 UTC, heavenshell commented on doq/parser.py
> +                else: # bare raise
Flake8 error `E261 at least two spaces before inline comment`
Please add another space before `#`

2022-01-03 10:14 UTC, heavenshell commented on tests/test_parser.py
> +    def test_bare_raise(self):
`E301 expected 1 blank line, found 0`
Please add blank line before `def` line.

2022-01-03 16:39 UTC, diego-ponce commented
Updated to fix flake8 errors.

2022-01-04 16:27 UTC, heavenshell approved these changes
Thank you LGTM!
I'll release to pypi in few days.

2022-01-04 16:28 UTC, merged